// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Nov 29 23:55:35 2022

InputUnit InputUnit_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.ROW(ROW_sig) ,	// input [3:0] ROW_sig
	.COLUMN(COLUMN_sig) ,	// output [3:0] COLUMN_sig
	.OUTPUT(OUTPUT_sig) ,	// output [7:0] OUTPUT_sig
	.check(check_sig) ,	// output  check_sig
	.junk(junk_sig) 	// output  junk_sig
);

