// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Thu Nov 17 08:45:28 2022

shift_reg shift_reg_inst
(
	.trig(trig_sig) ,	// input  trig_sig
	.reset(reset_sig) ,	// input  reset_sig
	.dir(dir_sig) ,	// input  dir_sig
	.in(in_sig) ,	// input [WIDTH-1:0] in_sig
	.out(out_sig) 	// output [COUNT*WIDTH-1:0] out_sig
);

defparam shift_reg_inst.COUNT = 4;
defparam shift_reg_inst.WIDTH = 4;
