// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Thu Nov 17 16:42:36 2022

Four2OneMUX Four2OneMUX_inst
(
	.S(S_sig) ,	// input  S_sig
	.D0(D0_sig) ,	// input [N-1:0] D0_sig
	.D1(D1_sig) ,	// input [N-1:0] D1_sig
	.D2(D2_sig) ,	// input [N-1:0] D2_sig
	.D3(D3_sig) ,	// input [N-1:0] D3_sig
	.Y(Y_sig) 	// output [N-1:0] Y_sig
);

defparam Four2OneMUX_inst.N = 4;
